### ISSUE TITLE
Edit/Delete

### ISSUE THREAD

**Issue by ElvisJG** [Lambda-School-Labs/property-manager-fe#107]
Landlords should be able to edit/delete properties, tenants, and workorders.
Renters should be able to edit/delete workorders

**Comment by hagnerd** [comment]
I'm not sure about some of this. We were a little reticent to make everything fully deletable and instead toyed around with the idea of making some resources "archivable" so that there is transparency and accounting for things.

**Comment by techturnip** [comment]
Edit functionality currently exists for Properties and Tenants

Work Orders need an edit functionality, perhaps as far as updating the "progress"

Delete/Archive functionality should be given thorough and careful consideration, currently there is no delete functionality implemented (at least not on the front-end) but I would recommend an archive functionality in general as it could be super beneficial in the event of accidental "removal" by a user, making it easy to revive a resource. But would add the need for garbage collection at some point.

**Comment by nickdurbin** [comment]
We implemented CRUD for all aspects. Going to close this issue.
